<a href="https://colab.research.google.com/github/ronniesong0809/ml-with-python/blob/master/mnist.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%tensorflow_version 2.x
import tensorflow as tf
import tensorflow.keras as keras
import numpy as np

TensorFlow 2.x selected.


In [0]:
mnist = keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train/255.0, x_test/255.0

In [0]:
model = keras.models.Sequential([
  keras.layers.Flatten(input_shape=(28,28)),
  keras.layers.Dense(128, activation='relu'),
  keras.layers.Dropout(0.2),
  keras.layers.Dense(10)
])

In [4]:
predictions = model(x_train[:1]).numpy()
predictions


If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.



array([[ 0.37415528, -0.47268048, -1.0390528 , -0.28945753, -0.3120619 ,
        -0.48630047, -0.04431381, -0.5146599 ,  0.97602916, -0.03247346]],
      dtype=float32)

In [5]:
tf.nn.softmax(predictions).numpy

<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[0.14983097, 0.06424295, 0.03646306, 0.07716106, 0.07543645,
        0.06337389, 0.09859679, 0.06160189, 0.27352187, 0.09977114]],
      dtype=float32)>>

In [0]:
loss_fn = keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [7]:
loss_fn(y_train[:1], predictions).numpy()

2.7587032

In [0]:
model.compile(optimizer='adam', loss=loss_fn, metrics=['accuracy'])

In [9]:
model.fit(x_train,y_train, epochs=5)

Train on 60000 samples
Epoch 1/5
60000/60000 [==============================] - 5s 77us/sample - loss: 0.2940 - accuracy: 0.9151
Epoch 2/5
60000/60000 [==============================] - 4s 72us/sample - loss: 0.1422 - accuracy: 0.9578
Epoch 3/5
60000/60000 [==============================] - 4s 72us/sample - loss: 0.1103 - accuracy: 0.9660
Epoch 4/5
60000/60000 [==============================] - 4s 73us/sample - loss: 0.0899 - accuracy: 0.9722
Epoch 5/5
60000/60000 [==============================] - 4s 71us/sample - loss: 0.0742 - accuracy: 0.9771


In [10]:
model.evaluate(x_test, y_test, verbose=2)

10000/10000 - 0s - loss: 0.0755 - accuracy: 0.9762


[0.07552368337172083, 0.9762]

In [11]:
probability_model = keras.Sequential([model, keras.layers.Softmax()])
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.76678601e-08, 1.58331528e-10, 2.76256401e-07, 1.72674438e-04,
        2.63389068e-11, 1.55140285e-07, 1.40548529e-13, 9.99826372e-01,
        1.24499294e-07, 5.06462641e-07],
       [2.05024597e-09, 5.71559998e-04, 9.99416590e-01, 9.18286605e-06,
        3.32359075e-12, 1.89745640e-06, 1.38096743e-08, 2.27709399e-13,
        8.76208105e-07, 1.36061181e-14],
       [2.10034017e-07, 9.99053657e-01, 4.53971297e-05, 2.30294118e-05,
        3.75770833e-05, 1.75379319e-06, 1.38052728e-05, 3.51056660e-04,
        4.73060180e-04, 4.57898011e-07],
       [9.99785006e-01, 3.70251989e-08, 1.24141137e-04, 2.75529572e-07,
        1.25864545e-08, 7.02696616e-06, 6.01551474e-05, 2.24844262e-05,
        7.19764088e-08, 8.69137750e-07],
       [1.80767347e-05, 3.98990974e-09, 1.25190913e-04, 4.97705105e-06,
        9.91799116e-01, 1.23002363e-04, 1.36829431e-05, 1.09428482e-03,
        1.18727257e-04, 6.70291018e-03]], dtype=float32)>